server:
  port: 8084
  servlet:
    #contextPath: /payment-service/api/payment
    contextPath: /api/v1/payment
 # This spring boot configuration enforce HTTPS and encrypted communication.
 # encrypt data between servers and users
  ssl:
    enabled: true
    key-alias: 1
    key-store-type: JKS
    key-store: classpath:keystore.jks
    #key-store: ${SSL_KEYSTORE}
    key-store-password: Passw0rd1
    #key-store-password: ${SSL_PASSWORD}
    #trust-store-type: JKS
    #trust-store: classpath:truststore.jks
    #trust-store: ${SSL_TRUSTSTORE}
    #trust-store-password: changeit
  error:
   include-message: always
   include-binding-error: always

poller:
  #auto-refresh-pmt-status-cron: 0 0/30 * * * * # runs at 00 and 30 minutes of every hour
  auto-refresh-pmt-status-cron: 0 0/05 * * * *

job:
  delay:
    ms: 120000 # 2 mins

feature:
  pmt-insight-flag: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true # By default, this is true
    fetch-registry: true
    healthcheck:
      enabled: true

management:
  health:
    jms:
      enabled: false
  #security:
    #enabled: false
#  endpoints:
#    web:
#      exposure:
#        include: health

# start activemq broker from command prompt - C:\apache-activemq-6.0.1\bin>activemq start
# we can access the ActiveMQ console using http://localhost:8161
activemq:
  broker-url: tcp://localhost:61616?jms.redeliveryPolicy.maximumRedeliveries=1
  user: admin
  password: admin
  packages:
    trust-all: true

payment:
  queue: payment-queue

order:
  queue: order-queue

kafka:
  topics:
    order-events--dlq: ORDER-EVENTS-DLQ-TOPIC
    payment: PAYMENT-PROCESS-TOPIC
    partitions: 3
    replication:
      factor: 1

logging:
  level:
    org:
      springframework:
        security: DEBUG

# Keycloak settings
jwt:
  auth:
    converter:
      resource-id: payment-service-client
      principle-attribute: admin

resilience4j:
  retry:
    instances:
      orderProcessingRetry:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - java.net.ConnectException
          - java.sql.SQLTransientException
          - java.util.concurrent.TimeoutException

  circuitbreaker:
    instances:
      orderProcessingCircuitBreaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        minimum-number-of-calls: 5
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - org.apache.kafka.common.errors.TimeoutException
          - org.apache.kafka.common.errors.NetworkException
          - org.apache.kafka.common.errors.UnknownTopicOrPartitionException
          - org.apache.kafka.common.errors.NotLeaderForPartitionException
          - java.net.ConnectException
          - java.util.concurrent.ExecutionException
          - java.lang.RuntimeException
spring:
  application: 'payment-service'
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/payment-realm
          jwk-set-uri: http://localhost:8080/realms/payment-realm/protocol/openid-connect/certs
  kafka:
    properties:
      schema.registry.url: http://192.168.0.143:9021
    bootstrap-servers: localhost:9094,localhost:9093
    producer:
      acks: all
      linger-ms: 0
      properties:
        enable:
          idempotence: true
    consumer:
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            use:
              type:
                headers: false
            trusted:
              packages: com.neo.api.common.*
            value:
              default:
                type: com.neo.api.common.order.event.OrderEvent
    listener:
      ack-mode: manual
    admin:
      enabled: false
      bootstrap-servers: localhost:9092,localhost:9093 # Forces KafkaAdmin to only use bootstrap servers, avoids trying internal network addresses that are unreachable.
      auto-create: false
      fail-fast: false

  cloud:
    compatibility-verifier:
      enabled: false
  config:
    activate:
      on-profile: dev
  sql:
    init:
      mode: never

  # First start MYSQL DB instance on your local server - located at windows/system services
  datasource:
    url: jdbc:mysql://localhost:3306/sumandb
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      generate_statistics: true
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
  jpa:
    #open-in-view: true
    generate-ddl: true

  #datasource:
  #  hikari:
  #    allow-pool-suspension: true
  #  url: jdbc:h2:~/test
  #  username: SA
  #  password:
  #  driverClassName: org.h2.Driver
  #  defaultSchema:
  #  maxPoolSize: 10
  #  hibernate:
  #   hbm2ddl.method: create-drop
  #    show_sql: true
  #    format_sql: true
  #jpa:
  #  properties:
  #    hibernate:
  #      temp:
  #        use_jdbc_metadata_defaults: false
  #      dialect: org.hibernate.dialect.H2Dialect
  #  hibernate:
      #ddl-auto: create
  #  ddl-auto: update
  #  database-platform: org.hibernate.dialect.H2Dialect

# link to access the swagger page - https://localhost:8088/payment-service/api/payment/swagger-ui.html
springdoc:
  swagger-ui:
    query-config-enabled: true
    use-root-path: true
  packagesToScan: 'com'
  pathsToMatch: '/**'

connect:
  service:
    payment:
      url: https://localhost:8071/connect
    auth:
      url: https://localhost:8071/connect
      client:
        id: test
        secret: test

payment-gateway:
  queue: payment-queue
  ssl:
    trust-store: classpath:truststore.payment.dev.jks
    trust-store-password: Passw0rd1
  service:
    connection-timeout: 1000
    #url: https://localhost:8086/payment-gateways-service/api/payments/process
    url: http://localhost:8086/payment-gateways-service/api/payments/process
    auth:
      url: https://localhost:8071/api/auth
      client-id:
      client-secret: test

#  jks: classpath:keystore.jks
#  jks-password: Password1
#  http-client:
#    proxy:
#      server:
#        port: 8080

#client:
#  jks: classpath:truststore.jks
  #jks: ${PAYMENT_CLIENT_TRUSTSTORE}
#  jks-password: Password1

#JMS
servers:
  jms:
    receiveTimeout: 5000 # Set the timeout to use for receive calls (in milliseconds)
    timeToLive: 5000 # Set the time-to-live of the message when sending (in milliseconds)
#    mq:
#      keyStoreFile: file:/etc/mqcerts/keystore.jks
#      keyStorePassword:

# Use IBM MQ server config to connect with queue - you need to install and run IBM MQ on your localhost
#ibm:
  #mq:
    #queueManager: QM1
    #channel: DEV.ADMIN.SVRCONN
    #connName: localhost(1414)
    #user: admin
    #password: passw0rd
    #useIBMCipherMappings: false
#   sslCipherSuit: TLS_RSA_WITH_AES_256_CBC_SHA256
