---
apiVersion: v1
kind: Secret
metadata:
  name: ssl-certs-secret
type: 'Opaque'
data:
{{ toYaml.Values.server.ssl.citiConnect.auth | indent 2 }}
{{ toYaml.Values.server.ssl.citiConnect.payment | indent 2 }}

