spring:
 cloud:
  config:
   server:
    #git:
    # uri: https://github.com/your-repo/config-repo
    # clone-on-start: true
    # search-paths: '{application}'
    native:
     #search-locations: classpath:/config/${environment}, classpath:/config/${environment}/{application}
    search-locations: classpath:/config, classpath:/config/{application}