# dev configuration for swift workflow application
server:
  port: 8089
  servlet:
    contextPath: /api
  error:
    include-message: always
    include-binding-error: always

management:
  endpoints:
    web:
      exposure:
        include: refresh, health