replicaCount: 2

image:
  repository: orders-service
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  #type: ClusterIP # please note that custer ip is not accessible from outside cluster.
  type: NodePort # NodePort is accessible from outside cluster
  port: 8080

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

env: dev

labels:
  app: orders
  component: backend
