# dev configuration for api gateway application
server:
  port: 8083
  #servlet:
  #  contextPath: /api
  error:
    include-message: always
    include-binding-error: always
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

keycloak:
  #get-token-url: http://localhost:8080/realms/tesco-dev/protocol/openid-connect/token
  base-url: http://localhost:8080
  client-id: tesco-api-client
  client-secret: Ayt2mxIngJYqjE8JzY3RCnBoP0U5Tq3a

spring:
  webflux:
    base-path: /api
  main:
    web-application-type: reactive # set web application type - reactive
  application:
    name: external-tenant-client
  redis: # make sure redis server running on default port 6379
    host: 192.168.99.100
    port: 6379